site_name: Esper API Wrapper
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'yellow'
  favicon: './assets/icon.ico'
  logo: './assets/esper-logo-trimmed.svg'
  font:
    text: 'Proxima Nova'
    code: 'Proxima Nova Mono'
repo_name: 'esperhq/esper-api'
repo_url: 'https://github.com/esperhq/esper-api'
extra_css: [esperStyle.css]
